<!DOCTYPE hmtl>
<html>
<head>
<title>Falcon social demo app</title>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="css/screen.css">
</head>
<body>
<div class="container">
	<header>
		<h1>my linkedin connections (<span class="count"></span>)</h1>
		<p class="info">
			This is a quick overview of the industries your connections is in
		</d>
	</header>
    <div class="linkedin">

    	<div class="industries">
			<div class="svg">
				<svg></svg>
			</div>
			<div class="industry-list"></div>
    	</div>
        <div class="connections">
        	<div class="download"><a href="#" class="csv">Download csv</a></div>
          <div class="names"></div>
        </div>

        <div class="profile">
        	<img src="images/missing.jpeg">	
        	<div>
        		<p class="headline"></p>
        		<p class="name"></p>
				<p class="headline">Industry</p>
				<p class="industry"></p>
				<p class="headline">Skills</p>
				<div class="skills"></div>
        	</div>
        </div>
    </div>
  <script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="js/d3.v3.js"></script>
  <script type="text/javascript" src="js/main.js"></script>
</body>
</html>